# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5aa6f51e91ba67b50972c0407d9e689a6af26651fce86dcc002afb3b7687d851e510a2704aaf67b197144bf3621b9279b0ee63eda81af8e3cce92bae1e90076

test:
  secret_key_base: 33d440edd0105363d649a1b1adf45d6cb7e78b1bcee17ca2ee9693fb8896c9fe254b251a4cd77c63b9f969db3cd5b386b2df029c078fc50962eb2d8f15a9b8e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
